# Generated by Django 5.2.17 on 2026-09-06 10:22

from django.db import migrations


def populate_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    default_categories = [
        'Groceries', 'Market', 'Rent', 'Electricity', 'Water', 
        'Gas', 'Internet', 'Cleaning', 'Transportation', 'Maintenance', 'Other'
    ]
    for category_name in default_categories:
        ExpenseCategory.objects.get_or_create(name=category_name)

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
