# Generated by Django 5.2.17 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_populate_default_categories'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['household', 'expense_date'], name='expenses_ex_househo_2b5221_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by', 'expense_date'], name='expenses_ex_paid_by_d338b8_idx'),
        ),
    ]
