# Generated by Django 5.2.17 on 2026-09-18 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('DELETE_EXPENSE', 'Delete Expense'), ('CREATE_MEAL', 'Create Meal'), ('UPDATE_MEAL', 'Update Meal'), ('DELETE_MEAL', 'Delete Meal'), ('ADD_DEPOSIT', 'Add Deposit'), ('UPDATE_DEPOSIT', 'Update Deposit'), ('DELETE_DEPOSIT', 'Delete Deposit'), ('INVITE_MEMBER', 'Invite Member'), ('REMOVE_MEMBER', 'Remove Member'), ('CREATE_SETTLEMENT', 'Create Settlement'), ('FINALIZE_SETTLEMENT', 'Finalize Settlement')], max_length=50)),
                ('entity', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='households.household')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
