# Generated by Django 5.2.17 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['household', 'deposit_date'], name='deposits_de_househo_da59df_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['member', 'deposit_date'], name='deposits_de_member__6b39aa_idx'),
        ),
    ]
