# Generated by Django 5.2.17 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['household', 'year', 'month'], name='settlements_househo_e7bb8f_idx'),
        ),
    ]
