# Generated by Django 5.2.17 on 2026-09-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('lunch', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('dinner', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('guest_meals', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='households.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='households.householdmember')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('household', 'member', 'date')},
            },
        ),
    ]
