# Generated by Django 5.2.17 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['household', 'date'], name='meals_meal_househo_75a7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['member', 'date'], name='meals_meal_member__18340e_idx'),
        ),
    ]
